import { useState, useEffect } from "react";
import Head from "next/head";
import styles from "../styles/Home.module.css";

import { fetcher } from "../lib/toolsService";
import useSWR from "swr";

export async function getStaticProps() {
  // Get external data from the file system, API, DB, etc.
  const toolsData = await fetcher(
    "https://docs.google.com/spreadsheets/d/e/2PACX-1vSQGpf0mHI9icmvtoYou7RkRMOZhe4_ndafoYqmSjGGuL9nl4iZwVGsgbEDlaI9EtjDyiZz7nY5ip6p/pub?output=csv"
  );

  // The value of the `props` key will be
  //  passed to the `Home` component
  return {
    props: {
      toolsData,
    },
  };
}

export default function Home(props) {

  const preFetchedToolsData = props.toolsData;
  const [toolsData, setToolsData] = useState([...props.toolsData]);
  const [isUpdatedDataAvailable, setIsUpdatedDataAvailable] = useState(false);

  const {data, error} = useSWR('https://docs.google.com/spreadsheets/d/e/2PACX-1vSQGpf0mHI9icmvtoYou7RkRMOZhe4_ndafoYqmSjGGuL9nl4iZwVGsgbEDlaI9EtjDyiZz7nY5ip6p/pub?output=csv', fetcher);

  if(error) return(<div>Erro! {error}</div>)

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        Yooooo
        {data ?
        data.map((tool, index) => {
          return <div key={index}>{tool["nome"]}</div>;
        })
        :
        preFetchedToolsData.map((tool, index) => {
          return <div key={index}>{tool["nome"]}</div>;
        })
        }
      </div>
    </div>
  );
}
