import { useState, useEffect } from "react";
import yaml from 'js-yaml'

import Head from "next/head";
import styles from "../styles/Home.module.css";

// import yamlData from '../public/data/tools.yml';

// export async function getStaticProps() {
//   // Get external data from the file system, API, DB, etc.
//   const toolsData = yamlData;
//   // The value of the `props` key will be
//   //  passed to the `Home` component
//   return {
//     props: {
//       toolsData,
//     },
//   };
// }

export default function Home(props) {
  
  // const [toolsData, setToolsData] = useState([...props.toolsData.tools]);
  const [toolsData, setToolsData] = useState([]);

  const getUpdatedData = async() => {
    const updatedData = await fetch('/data/tools.yml').then(res => res.text()).then(data => yaml.load(data));
    console.log(updatedData);
    setToolsData([...updatedData.tools]);
  }

  useEffect(()=>{
    getUpdatedData();
  }, [])

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        {toolsData.length > 0 ?
        toolsData.map((tool, index) => {
          return <div key={index}>{tool.nome}</div>;
        })
        :
        <div>Loading...</div>
        }
      </div>
    </div>
  );
}
